version: '3.4'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=HRM;User Id=sa;Password=HelloWorld09@@;TrustServerCertificate=True
      - ConnectionStrings__Connection=XpoProvider=MSSqlServer;Server=db,1433;Database=HRM;User Id=sa;Password=HelloWorld09@@;TrustServerCertificate=True
      - UnderProxy=true
    ports:
      - '5276:443'
      - '5277:80'
    depends_on:
      db:
        condition: service_started
